image: Visual Studio 2017
version: 18.02-build{build}
environment:
  version: 18.02
install:
- ps: >-
    New-Item -ItemType Directory lib | Out-Null

    Push-Location lib

    New-Item -ItemType Directory bin,lib,include | Out-Null

    Invoke-WebRequest https://www.libsdl.org/release/SDL2-devel-2.0.7-VC.zip -OutFile sdl2.zip

    7z x sdl2.zip

    Copy-Item .\SDL2-2.0.7\include\ -Recurse -Destination include\sdl2

    Copy-Item .\SDL2-2.0.7\lib\x86\*.dll -Destination bin

    Copy-Item .\SDL2-2.0.7\lib\x86\*.lib -Destination lib

    Remove-Item .\sdl2.zip

    Remove-Item -Recurse .\SDL2-2.0.7

    Pop-Location
configuration: Release
build:
  verbosity: minimal
after_build:
- ps: >-
    New-Item -ItemType Directory artefacts | Out-Null

    Copy-Item CHANGELOG.md,LICENSE,bin\openloco.dll,lib\bin\SDL2.dll artefacts

    Copy-Item loco.exe artefacts\openloco.exe

    Push-Location artefacts

    7z a -tzip -mx9 -mtc=off -r openloco-v${env:version}-win32.zip *

    Pop-Location

artifacts:
- path: 'artefacts\openloco-v$(version)-win32.zip'
deploy:
  provider: GitHub
  auth_token:
    secure: 49K/y43epwh5Sb8uY1l/TbIFRPcEq6fraQaYGS0bgWQJfONznd6hCqPUCg7WSX16
  artifact: artefacts\openloco-v$(version)-win32.zip
  draft: true
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
